### PR TITLE
[CC-49: BugFix] Mismatch of mobile number between frontend validation and backend validation

### PR DESCRIPTION
**Pull request by VanderDeng**
### Descriptions

- Link to Jira ticket here:https://leonhard.atlassian.net/jira/software/projects/CC/boards/2?selectedIssue=CC-49
- Link to Figma:

### Provide screenshots or videos that the function is working.

https://user-images.githubusercontent.com/49120762/201239335-74526f96-85e7-451e-9257-ae01f98d7332.mov

### Provide screenshots of no warning, or error in the console.
image
image
image
image

- [x] No merge conflict with the `main` branch, make sure your code is up to date with `main`.
- [x] Check PR title is aligned with your ticket, (i.e `[CC-xx: Feature] Create pull request template`).
- [x] Check your app will run without crashes.
- [x] Check if there are hard-coded values.
- [x] No `//eslint-disable-next-line no-unused-vars`, unless otherwise specified.
- [x] No unnecessary spaces between lines of code.
- [x] Check you are using `camelCase && PascalCase` correctly.
- [x] Check you named your code properly.
- [x] Remove unused comments.

### CODE REVIEW

**Comment by NorrisWu0** [comment]
Have you tried other cases like these?
- 0421234567
- 3 1234 5678
- 07 1234 5678
- 86 1234 567 8901

**Comment by VanderDeng** [comment]
> 

Done, I uploaded the screenshots of these test numbers

**Comment by VanderDeng** [comment]
> Have you tried other cases like these?
> 
> * 0421234567
> * 3 1234 5678
> * 07 1234 5678
> * 86 1234 567 8901

Done, I uploaded the screenshots of these test numbers

**Review by NorrisWu0 — APPROVED** [review]

**Review by jiayuu-u — APPROVED** [review]
LGTM

**Pull request merged**
