### PR TITLE
[CC-xx] Set up GitHub action and pr template

### PR DESCRIPTION
**Pull request by NorrisWu0**
### Descriptions

- Link to Jira ticket here: `N/A`
- Link to Figma: `N/A`

### Provide screenshots or videos that the function is working.

- No screenshot is available for this pr, but you will find GitHub Action running in this commit

### Provide screenshots of no warning, or error in the console.

You should find [feat: add pr template for developers](https://github.com/courtcanva/cc-multiverse/pull/7/commits/51d6bf61c63bf2f9a39a169c4d3bc3e5e21ef693) commit failed due to type in the workflow file, and [fix: typo in sanity-check workflow](https://github.com/courtcanva/cc-multiverse/pull/7/commits/64d1c61135d76c9835165ae37275ced67e257669) commit came out success.

- [x] No merge conflict with the `main` branch, make sure your code is up to date with `main`.
- [x] Check PR title is aligned with your ticket, (i.e `[CC-xx: Feature] Create pull request template`).
- [x] Check your app will run without crashes.
- [x] Check if there are hard-coded values.
- [x] No `//eslint-disable-next-line no-unused-vars`, unless otherwise specified.
- [x] No unnecessary spaces between lines of code.
- [x] Check you are using `camelCase && PascalCase` correctly.
- [x] Check you named your code properly.
- [x] Remove unused comments.

### CODE REVIEW

**Comment by NorrisWu0** [comment]
Just a side note, we have all the GitHub steps wrapped in one workflow, but we can have them separated in individual workflows if we want to.

**Review by Cameron933 — APPROVED** [review]
Good job, good template

**Comment by VanderDeng** [comment]
LGTM

**Review by VanderDeng — APPROVED** [review]
LGTM

**Pull request merged**
